server:
<<<<<<< HEAD
  port: 8087
=======
  port : 8087
>>>>>>> ddd55dd52c4f338a1ec271afdfdf0cef8fbccb39
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/sbb_2nd?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
<<<<<<< HEAD
        dialect: org.hibernate.dialect.MariaDB103Dialect
=======
        dialect:  org.hibernate.dialect.MariaDB103Dialect
>>>>>>> ddd55dd52c4f338a1ec271afdfdf0cef8fbccb39
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace